-- 코드를 작성해주세요
SELECT ED.ID,
       CASE
            WHEN ED.PERCENT <= 0.25 THEN 'CRITICAL'
            WHEN ED.PERCENT <= 0.5 THEN 'HIGH'
            WHEN ED.PERCENT <= 0.75 THEN 'MEDIUM'
            ELSE 'LOW'
        END AS 'COLONY_NAME'
FROM (SELECT ID,
             PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PERCENT
      FROM ECOLI_DATA) AS ED
ORDER BY ED.ID;