-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * O.AMOUNT AS TOTAL
FROM FOOD_PRODUCT P
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT, PRODUCE_DATE
      FROM FOOD_ORDER 
      WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
      GROUP BY PRODUCT_ID) O
      ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL DESC, PRODUCT_ID ASC;