SELECT COUNT(*) AS FISH_COUNT, S.MAX_LENGTH, F.FISH_TYPE
FROM FISH_INFO F
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
      FROM FISH_INFO
      GROUP BY FISH_TYPE HAVING AVG(IFNULL(LENGTH, 10) >= 33)) S 
ON F.FISH_TYPE = S.FISH_TYPE
GROUP BY F.FISH_TYPE
ORDER BY FISH_TYPE ASC;

